In [1]:
import pandas as pd

In [2]:
vicreg_csv = pd.read_csv('/home/fsoto/Documents/LCsSSL/wandb_csv/hp_augmentations/single_aug_hp.csv')

In [3]:
AUGS_DIRECTORY = "/home/fsoto/Documents/LCsSSL/wandb_csv/hp_augmentations"

## Amplitude Inverse

In [4]:
amplitude_inverse_csv = pd.read_csv(f"{AUGS_DIRECTORY}/amplitude_inverse.csv") 
amplitude_inverse_hp = vicreg_csv[vicreg_csv['data.aug_names_list'] == '["amplitude_inverse"]'].sort_values(by='Created', ascending=True).reset_index(drop=True)
amplitude_inverse_hps= ['data.amplitude_inverse_prob']
amplitude_inverse_hp = amplitude_inverse_hp[amplitude_inverse_hps]
grouped_amplitude_inverse_f1 = amplitude_inverse_csv.groupby('model.pre_trained_iteration')['val/f1'].agg(['mean', 'std'])
grouped_amplitude_inverse_f1.join(amplitude_inverse_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False)

                                 mean       std  data.amplitude_inverse_prob
model.pre_trained_iteration
2                            0.396929  0.009962                          0.3
3                            0.396052  0.005466                          0.5
0                            0.393451  0.010060                          0.1
1                            0.390592  0.010164                          0.2

## Random Scaling

In [5]:
random_scaling_csv = pd.read_csv(f"{AUGS_DIRECTORY}/random_scaling.csv")
random_scaling_hp = vicreg_csv[vicreg_csv['data.aug_names_list'] == '["random_scaling"]'].sort_values(by='Created', ascending=True).reset_index(drop=True)
random_scaling_hps = ['data.scaling_prob','data.scaling_sigma']
random_scaling_hp = random_scaling_hp[random_scaling_hps]
grouped_random_scaling_f1 = random_scaling_csv.groupby('model.pre_trained_iteration')['val/f1'].agg(['mean', 'std'])
grouped_random_scaling_f1.join(random_scaling_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False)

,mean,std,data.scaling_prob,data.scaling_sigma
model.pre_trained_iteration,,,,
5,0.409736,0.010399,0.8,0.5
4,0.408354,0.012421,0.5,0.5
3,0.406694,0.011210,0.2,0.5
6,0.402349,0.008771,0.2,0.8
0,0.400846,0.014552,0.2,0.1
1,0.399437,0.016633,0.5,0.1
2,0.394130,0.015232,0.8,0.1
7,0.378971,0.011527,0.5,0.8
8,0.355142,0.013625,0.8,0.8

## Random Masking

In [6]:
random_masking_csv = pd.read_csv(f"{AUGS_DIRECTORY}/random_masking.csv")
random_masking_hp = vicreg_csv[vicreg_csv['data.aug_names_list'] == '["random_mask"]'].sort_values(by='Created', ascending=True).reset_index(drop=True)
random_maskinng_hps = ['data.random_mask_prob']
random_masking_hp = random_masking_hp[random_maskinng_hps]
grouped_random_masking_f1 = random_masking_csv.groupby('model.pre_trained_iteration')['val/f1'].agg(['mean', 'std'])
grouped_random_masking_f1.join(random_masking_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False)

                                 mean       std  data.random_mask_prob
model.pre_trained_iteration
3                            0.547798  0.004151                    0.8
2                            0.546263  0.007803                    0.6
1                            0.522780  0.008282                    0.5
0                            0.476179  0.008534                    0.3

## Time Shift

In [7]:
time_shift_csv = pd.read_csv(f"{AUGS_DIRECTORY}/time_shift.csv")
time_shift_hp = vicreg_csv[vicreg_csv['data.aug_names_list'] == '["time_shift"]'].sort_values(by='Created', ascending=True).reset_index(drop=True)
time_shift_hps = ['data.time_shift_prob', 'data.time_shift_range']
time_shift_hp = time_shift_hp[time_shift_hps]
grouped_time_shift_f1 = time_shift_csv.groupby('model.pre_trained_iteration')['val/f1'].agg(['mean', 'std'])
grouped_time_shift_f1.join(time_shift_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False)

,mean,std,data.time_shift_prob,data.time_shift_range
model.pre_trained_iteration,,,,
1,0.427884,0.012187,0.5,5.0
6,0.424730,0.010958,0.2,75.0
0,0.424253,0.011359,0.2,5.0
3,0.423746,0.011558,0.2,25.0
7,0.423081,0.012175,0.5,75.0
8,0.422037,0.010840,0.8,75.0
2,0.420901,0.011888,0.8,5.0
4,0.420453,0.012956,0.5,25.0
5,0.417906,0.013428,0.8,25.0

## Jitter

In [8]:
jitter_csv = pd.read_csv(f"{AUGS_DIRECTORY}/jitter.csv")
jitter_hp = vicreg_csv[vicreg_csv['data.aug_names_list'] == '["jitter"]'].sort_values(by='Created', ascending=True).reset_index(drop=True)
jitter_hps = ['data.jitter_prob', 'data.jitter_sigma']
jitter_hp = jitter_hp[jitter_hps]
grouped_jitter_f1 = jitter_csv.groupby('model.pre_trained_iteration')['val/f1'].agg(['mean', 'std'])
grouped_jitter_f1.join(jitter_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False)

,mean,std,data.jitter_prob,data.jitter_sigma
model.pre_trained_iteration,,,,
8,0.431656,0.009002,0.8,0.015
5,0.425726,0.011258,0.8,0.010
7,0.424676,0.009439,0.5,0.015
4,0.422514,0.010907,0.5,0.010
2,0.418352,0.012071,0.8,0.005
1,0.412281,0.010966,0.5,0.005
6,0.410675,0.008215,0.2,0.015
3,0.407535,0.009088,0.2,0.010
0,0.404054,0.011454,0.2,0.005

## Channel Shuffle

In [9]:
channel_shuffle_csv = pd.read_csv(f"{AUGS_DIRECTORY}/channel_shuffle.csv")
channel_shuffle_hp = vicreg_csv[vicreg_csv['data.aug_names_list'] == '["channel_shuffle"]'].sort_values(by='Created', ascending=True).reset_index(drop=True)
channel_shuffle_hps = ['data.channel_shuffling_prob']
channel_shuffle_hp = channel_shuffle_hp[channel_shuffle_hps]
grouped_channel_shuffle_f1 = channel_shuffle_csv.groupby('model.pre_trained_iteration')['val/f1'].agg(['mean', 'std'])
grouped_channel_shuffle_f1.join(channel_shuffle_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False)

                                 mean       std  data.channel_shuffling_prob
model.pre_trained_iteration
2                            0.516011  0.013524                          0.8
0                            0.481453  0.007612                          0.2
1                            0.462961  0.012253                          0.5

## Time Inverse

In [10]:
time_inverse_csv = pd.read_csv(f"{AUGS_DIRECTORY}/time_inverse.csv")
time_inverse_hp = vicreg_csv[vicreg_csv['data.aug_names_list'] == '["time_inverse"]'].sort_values(by='Created', ascending=True).reset_index(drop=True)
time_inverse_hps = ['data.flip_time_signal_prob']
time_inverse_hp = time_inverse_hp[time_inverse_hps]
grouped_time_inverse_f1 = time_inverse_csv.groupby('model.pre_trained_iteration')['val/f1'].agg(['mean', 'std'])
grouped_time_inverse_f1.join(time_inverse_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False)

                                 mean       std  data.flip_time_signal_prob
model.pre_trained_iteration
1                            0.421165  0.012694                         0.5
0                            0.421088  0.012499                         0.2
2                            0.420034  0.013596                         0.7

## Signal Resampling

In [11]:
signal_resampling_csv = pd.read_csv(f"{AUGS_DIRECTORY}/resampling.csv")
signal_resampling_hp = vicreg_csv[vicreg_csv['data.aug_names_list'] == '["resampling"]'].sort_values(by='Created', ascending=True).reset_index(drop=True)
signal_resampling_hps = ['data.signal_resampling_prob', 'data.signal_resampling_ratio']
signal_resampling_hp = signal_resampling_hp[signal_resampling_hps]
grouped_signal_resampling_f1 = signal_resampling_csv.groupby('model.pre_trained_iteration')['val/f1'].agg(['mean', 'std'])
grouped_signal_resampling_f1.join(signal_resampling_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False)

,mean,std,data.signal_resampling_prob,data.signal_resampling_ratio
model.pre_trained_iteration,,,,
5,0.544781,0.006628,0.8,0.5
8,0.543690,0.005818,0.8,0.8
4,0.542415,0.007492,0.5,0.5
7,0.541908,0.003921,0.5,0.8
6,0.531196,0.005914,0.2,0.8
3,0.523178,0.006159,0.2,0.5
2,0.507556,0.009608,0.8,0.2
1,0.500610,0.007128,0.5,0.2
0,0.442206,0.009897,0.2,0.2

## Stretch

In [12]:
stretch_csv = pd.read_csv(f"{AUGS_DIRECTORY}/stretch.csv")
stretch_hp = vicreg_csv[vicreg_csv['data.aug_names_list'] == '["stretch"]'].sort_values(by='Created', ascending=True).reset_index(drop=True)
stretch_hps = ['data.stretch_prob', 'data.stretch_sigma']
stretch_hp = stretch_hp[stretch_hps]
grouped_stretch_f1 = stretch_csv.groupby('model.pre_trained_iteration')['val/f1'].agg(['mean', 'std'])
grouped_stretch_f1.join(stretch_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False)

,mean,std,data.stretch_prob,data.stretch_sigma
model.pre_trained_iteration,,,,
6,0.424151,0.013368,0.2,0.0010
7,0.422086,0.013346,0.5,0.0010
8,0.422017,0.013644,0.8,0.0010
3,0.421462,0.015641,0.2,0.0005
4,0.421236,0.012389,0.5,0.0005
5,0.421108,0.014087,0.8,0.0005
1,0.420986,0.013606,0.5,0.0001
2,0.420979,0.013290,0.8,0.0001
0,0.419121,0.012827,0.2,0.0001

## Comparision

In [13]:
# Get the best configuration for each augmentation
best_configs = []

# Amplitude Inverse
best_amplitude_inverse = grouped_amplitude_inverse_f1.join(amplitude_inverse_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False).iloc[0]
best_amplitude_inverse['augmentation'] = 'amplitude_inverse'
best_configs.append(best_amplitude_inverse)

# Random Scaling
best_random_scaling = grouped_random_scaling_f1.join(random_scaling_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False).iloc[0]
best_random_scaling['augmentation'] = 'random_scaling'
best_configs.append(best_random_scaling)

# Random Masking
best_random_masking = grouped_random_masking_f1.join(random_masking_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False).iloc[0]
best_random_masking['augmentation'] = 'random_masking'
best_configs.append(best_random_masking)

# Time Shift
best_time_shift = grouped_time_shift_f1.join(time_shift_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False).iloc[0]
best_time_shift['augmentation'] = 'time_shift'
best_configs.append(best_time_shift)

# Jitter
best_jitter = grouped_jitter_f1.join(jitter_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False).iloc[0]
best_jitter['augmentation'] = 'jitter'
best_configs.append(best_jitter)

# Channel Shuffle
best_channel_shuffle = grouped_channel_shuffle_f1.join(channel_shuffle_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False).iloc[0]
best_channel_shuffle['augmentation'] = 'channel_shuffle'
best_configs.append(best_channel_shuffle)

# Time Inverse
best_time_inverse = grouped_time_inverse_f1.join(time_inverse_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False).iloc[0]
best_time_inverse['augmentation'] = 'time_inverse'
best_configs.append(best_time_inverse)

# Signal Resampling
best_signal_resampling = grouped_signal_resampling_f1.join(signal_resampling_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False).iloc[0]
best_signal_resampling['augmentation'] = 'signal_resampling'
best_configs.append(best_signal_resampling)

# Stretch
best_stretch = grouped_stretch_f1.join(stretch_hp, on='model.pre_trained_iteration', how='left', lsuffix='_f1', rsuffix='_hp').sort_values(by='mean', ascending=False).iloc[0]
best_stretch['augmentation'] = 'stretch'
best_configs.append(best_stretch)

# Create the comparison dataframe
best_augmentations_df = pd.DataFrame(best_configs)

# Reorder columns to put augmentation first
cols = ['augmentation'] + [col for col in best_augmentations_df.columns if col != 'augmentation']
best_augmentations_df = best_augmentations_df[cols]

# Sort by mean F1 score (descending)
best_augmentations_df = best_augmentations_df.sort_values(by='mean', ascending=False).reset_index(drop=True)

print("Best configuration for each augmentation:")
best_augmentations_df

Best configuration for each augmentation:

,augmentation,mean,std,data.amplitude_inverse_prob,data.scaling_prob,data.scaling_sigma,data.random_mask_prob,data.time_shift_prob,data.time_shift_range,data.jitter_prob,data.jitter_sigma,data.channel_shuffling_prob,data.flip_time_signal_prob,data.signal_resampling_prob,data.signal_resampling_ratio,data.stretch_prob,data.stretch_sigma
0,random_masking,0.547798,0.004151,NaN,NaN,NaN,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,signal_resampling,0.544781,0.006628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8,0.5,NaN,NaN
2,channel_shuffle,0.516011,0.013524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8,NaN,NaN,NaN,NaN,NaN
3,jitter,0.431656,0.009002,NaN,NaN,NaN,NaN,NaN,NaN,0.8,0.015,NaN,NaN,NaN,NaN,NaN,NaN
4,time_shift,0.427884,0.012187,NaN,NaN,NaN,NaN,0.5,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,stretch,0.424151,0.013368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,0.001
6,time_inverse,0.421165,0.012694,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN
7,random_scaling,0.409736,0.010399,NaN,0.8,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,amplitude_inverse,0.396929,0.009962,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN