In [1]:
import pandas as pd
import os
import yaml
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
results_csv = pd.read_csv('/home/fsoto/Documents/LCsSSL/wandb_csv/patch_model_comparison.csv')

In [3]:
results_csv.columns

Index(['Name', 'test/f1', 'data.split', 'Created', 'Runtime', 'Group',
       'End Time', 'ID', 'Notes', 'Tags',
       'callbacks.model_checkpoint.save_last', 'data.max_length',
       'data.num_workers', 'data.patch_size', 'data.percentage',
       'data.use_collate', 'model.freeze_lc_encoder',
       'model.lc_classifier._target_', 'model.lc_classifier.dropout',
       'model.lc_classifier.embedding_size', 'model.lc_net._target_',
       'model.lc_net.patch_size', 'model.optimizer.betas',
       'model.plot_all_epochs_cms', 'model.pre_trained_iteration',
       'model.pre_trained_lc_path', 'model/params/non_trainable',
       'model/params/total', 'model/params/trainable', 'tags',
       'trainer.max_epochs', 'cosine_schedule', 'epoch', 'test/f1_lc',
       'test/loss', 'test/loss_lc', 'train/f1', 'train/f1_lc', 'train/loss',
       'train/loss_lc', 'trainer/global_step', 'val/f1', 'val/f1_lc',
       'val/loss', 'val/loss_lc'],
      dtype='object')

In [4]:
results_csv

,Name,test/f1,data.split,Created,Runtime,Group,End Time,ID,Notes,Tags,...,test/loss_lc,train/f1,train/f1_lc,train/loss,train/loss_lc,trainer/global_step,val/f1,val/f1_lc,val/loss,val/loss_lc
0,major-wind-578,0.834053,4,2025-08-19T17:25:26.000Z,1033,patch_model,2025-08-19T17:42:39.000Z,f1i2hb3o,-,"atat_modified, full, linearCLF, multimodal, pe...",...,0.517432,0.905553,0.905553,0.286801,0.286801,13800,0.821847,0.821847,0.536572,0.536572
1,pretty-firebrand-577,0.821416,3,2025-08-19T17:10:10.000Z,915,patch_model,2025-08-19T17:25:25.000Z,j141g7y0,-,"atat_modified, full, linearCLF, multimodal, pe...",...,0.520260,0.893765,0.893765,0.324902,0.324902,12190,0.829297,0.829297,0.520546,0.520546
2,zesty-hill-576,0.835140,2,2025-08-19T16:53:21.000Z,1008,patch_model,2025-08-19T17:10:09.000Z,js5cfrcd,-,"atat_modified, full, linearCLF, multimodal, pe...",...,0.520122,0.910480,0.910480,0.270258,0.270258,13455,0.835709,0.835709,0.544713,0.544713
3,brisk-sun-575,0.827927,1,2025-08-19T16:35:54.000Z,1046,patch_model,2025-08-19T16:53:20.000Z,s9j51vkt,-,"atat_modified, full, linearCLF, multimodal, pe...",...,0.527025,0.907036,0.907036,0.281882,0.281882,14145,0.820790,0.820790,0.562781,0.562781
4,feasible-galaxy-574,0.834689,0,2025-08-19T16:20:28.000Z,925,patch_model,2025-08-19T16:35:53.000Z,f4cr6jby,-,"atat_modified, full, linearCLF, multimodal, pe...",...,0.498293,0.901352,0.901352,0.297131,0.297131,13455,0.847932,0.847932,0.505602,0.505602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,eternal-haze-5,0.800810,1,2025-07-22T18:48:10.000Z,2180,baselines,2025-07-22T19:24:30.000Z,r8vtdj7x,-,"atat_modified, full, multimodal, periodic_classes",...,0.631658,0.873995,0.873995,0.386350,0.386350,6844,0.798267,0.798267,0.645906,0.645906
201,firm-resonance-4,0.835444,2,2025-07-22T18:44:54.000Z,2850,baselines,2025-07-22T19:32:24.000Z,x10km2mn,-,"atat_modified, full, multimodal, periodic_classes",...,0.491979,0.875089,0.875089,0.379812,0.379812,10695,0.822571,0.822571,0.574743,0.574743
202,dashing-silence-2,0.685205,0,2025-07-22T18:38:44.000Z,565,baselines,2025-07-22T18:48:09.000Z,ppeafcyw,-,"atat_modified, full, multimodal, periodic_classes",...,0.928090,0.757761,0.757761,0.713741,0.713741,1080,0.685802,0.685802,0.984448,0.984448
203,serene-sunset-3,0.772615,0,2025-07-22T18:38:44.000Z,1375,baselines,2025-07-22T19:01:39.000Z,y94jpgqi,-,"atat_modified, full, multimodal, periodic_classes",...,0.746453,0.854393,0.854393,0.439213,0.439213,3799,0.771223,0.771223,0.741049,0.741049
204,dry-galaxy-1,0.323332,0,2025-07-22T18:38:43.000Z,370,baselines,2025-07-22T18:44:53.000Z,cp7857j3,-,"atat_modified, full, multimodal, periodic_classes",...,1.839913,0.476386,0.476386,1.306209,1.306209,176,0.323086,0.323086,1.939878,1.939878

In [5]:
#group by Group column and data.percentage column, and get test/f1 column
grouped = results_csv.groupby(['Group', 'data.percentage']).agg({'test/f1': 'mean'}).reset_index()

In [6]:
# get the rows where Group is baselines and data percentage is 1.0 , and the rows where group is patch_model
filtered = results_csv[((results_csv['Group'] == 'baseline') & (results_csv['data.percentage'] == 1.0)) | (results_csv['Group'] == 'patch_model')]

In [7]:
#get test test/f1 column and group
test_f1 = filtered[['Group', 'data.percentage', 'test/f1','data.split']].sort_values(by=['Group', 'data.split'])

In [8]:
test_f1

          Group  data.percentage   test/f1  data.split
27     baseline              1.0  0.835117           0
13     baseline              1.0  0.839472           1
10     baseline              1.0  0.835647           2
7      baseline              1.0  0.837811           3
20     baseline              1.0  0.836668           4
4   patch_model              NaN  0.834689           0
3   patch_model              NaN  0.827927           1
2   patch_model              NaN  0.835140           2
1   patch_model              NaN  0.821416           3
0   patch_model              NaN  0.834053           4

In [9]:
from scipy import stats
f1s = test_f1[test_f1['Group'] == 'baseline']['test/f1'].values
compare_f1s = test_f1[test_f1['Group'] == 'patch_model']['test/f1'].values
t_stat, p_val = stats.ttest_ind(f1s, compare_f1s, equal_var=False, alternative='greater')

In [10]:
p_val

np.float64(0.03763909340097563)

In [11]:
from mlxtend.evaluate import permutation_test

In [12]:
compare_f1s

array([0.83468866, 0.82792705, 0.83514011, 0.8214159 , 0.83405316])

In [13]:
p_value = permutation_test(compare_f1s, f1s,
                           method='exact',
                           func='x_mean < y_mean',paired=True)
p_value

0.03125